#!/usr/bin/env python3
"""
Download the PRISM fonts locally so overlays work fully offline.

Fetches the Google Fonts CSS for Space Grotesk (400/500/600/700) and JetBrains
Mono (500/600/700), downloads every woff2 it references into ../fonts/, and
rewrites ../fonts/prism-fonts.css with local @font-face rules (preserving each
weight and unicode-range exactly as Google serves them).

Standard library only. Run on YOUR machine (the build sandbox can't reach the
font CDN). Re-runnable; safe to commit the results.
"""
import os
import re
import sys
import urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700"
           "&family=JetBrains+Mono:wght@500;600;700&display=swap")
# a modern browser UA so Google returns woff2 (not ttf)
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

FONTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "fonts")
FONTS_DIR = os.path.abspath(FONTS_DIR)


def _get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read() if binary else r.read().decode("utf-8")


def slug(family):
    return re.sub(r"[^a-z0-9]+", "-", family.lower()).strip("-")


def main():
    os.makedirs(FONTS_DIR, exist_ok=True)
    print("Fetching font CSS from Google...")
    css = _get(CSS_URL)

    blocks = re.findall(r"@font-face\s*{[^}]*}", css, re.S)
    if not blocks:
        sys.exit("No @font-face blocks found — Google may have changed its format.")

    out, counters, downloaded = [], {}, 0
    for b in blocks:
        fam = re.search(r"font-family:\s*'([^']+)'", b)
        wgt = re.search(r"font-weight:\s*(\d+)", b)
        url = re.search(r"src:\s*url\(([^)]+)\)\s*format\('woff2'\)", b)
        rng = re.search(r"unicode-range:\s*([^;]+);", b)
        if not (fam and wgt and url):
            continue
        family, weight, src = fam.group(1), wgt.group(1), url.group(1).strip("'\"")
        key = "%s-%s" % (slug(family), weight)
        counters[key] = counters.get(key, 0) + 1
        fname = "%s-%d.woff2" % (key, counters[key])

        print("  downloading %s  (%s %s)" % (fname, family, weight))
        with open(os.path.join(FONTS_DIR, fname), "wb") as f:
            f.write(_get(src, binary=True))
        downloaded += 1

        rule = ("@font-face{font-family:'%s';font-style:normal;font-weight:%s;"
                "font-display:swap;src:url('%s') format('woff2');" % (family, weight, fname))
        if rng:
            rule += "unicode-range:%s;" % rng.group(1).strip()
        rule += "}"
        out.append(rule)

    header = ("/* PRISM fonts — LOCAL (generated by scripts/fetch-fonts.py).\n"
              "   Delete this file's contents and restore the Google @import to\n"
              "   go back online. */\n")
    with open(os.path.join(FONTS_DIR, "prism-fonts.css"), "w", encoding="utf-8") as f:
        f.write(header + "\n".join(out) + "\n")

    print("Done: %d woff2 files -> %s" % (downloaded, FONTS_DIR))
    print("prism-fonts.css rewritten to use them. Commit the fonts + css.")


if __name__ == "__main__":
    main()
